# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: sudo apt-get install -y build-essential ncurses-base ncurses-bin libncurses5-dev dialog
  displayName: 'Get dependencies'

- bash: make wandboard_lancer_defconfig
  displayName: 'Set config'

- bash: make
  displayName: 'Build'
