# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: sudo apt-get install -y which sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar spio python unzip rsync file bc wget ncurses5 bazaar cvs git mercurial scp subversion asciidoc w3m dblatex graphviz python-matplotlib
  displayName: 'Get dependencies'

- bash: make wandboard_lancer_defconfig
  displayName: 'Set config'

- bash: make
  displayName: 'Build'
