name: Raspberry PI3 RootFS Build

on: push

jobs:
  my-job:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@2018.05
      env:
        br_config: raspberrypi3_lancer_defconfig
    - name: Build
      run: |
        make {{ $br_config}}
        make
