name: Raspberry PI3 RootFS Build

on: push

jobs:
  my-job:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 2018.05
      env:
        br_config: raspberrypi3_lancer_defconfig
    - name: Build
      run: |
        apt-get update
        apt-get install -y build-essential bc python 
        make raspberrypi3_lancer_defconfig
        make
